name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: "2.31.2"
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-build-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: cache-build-${{ runner.os }}-nix-store-
      - name: Build
        run: nix build
      - name: Archive objects
        # Skip archive if running on act
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: out.bin
          path: result
